[theme]
base                     = "light"
primaryColor             = "#ffd700"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor                = "#000000"
font                     = "sans serif"

[server]
headless        = true
maxUploadSize   = 50

[browser]
gatherUsageStats = false
